name: facebook_ui
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  device_preview: ^1.1.0
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.2
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/emojis/angry.svg
    - assets/emojis/heart.svg
    - assets/emojis/laughing.svg
    - assets/emojis/like.svg
    - assets/emojis/sad.svg
    - assets/emojis/shocked.svg
    - assets/wallpapers/1.jpeg
    - assets/wallpapers/2.jpeg
    - assets/wallpapers/3.jpeg
    - assets/wallpapers/4.jpeg
    - assets/wallpapers/5.jpeg
    - assets/wallpapers/6.jpeg
    - assets/users/1.jpg
    - assets/users/2.jpg
    - assets/users/3.jpg
    - assets/users/4.jpg
    - assets/users/5.jpg
    - assets/users/6.jpg
    - assets/users/7.jpg
    - assets/users/8.jpg
    - assets/publications/ferrari.jpeg
    - assets/publications/flutter.jpeg
    - assets/logos/facebook.svg
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
    - family: Nunito
      fonts:
        - asset: assets\fonts\Nunito\static\Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\Nunito\static\Nunito-ExtraLightItalic.ttf
          weight: 200
        - asset: assets\fonts\Nunito\static\Nunito-Light.ttf
          weight: 300
        - asset: assets\fonts\Nunito\static\Nunito-Italic.ttf
          weight: 300
        - asset: assets\fonts\Nunito\static\Nunito-Regular.ttf
          weight: 400
        - asset: assets\fonts\Nunito\static\Nunito-Medium.ttf
          weight: 500
        - asset: assets\fonts\Nunito\static\Nunito-MediumItalic.ttf
          weight: 500
        - asset: assets\fonts\Nunito\static\Nunito-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Nunito\static\Nunito-SemiBoldItalic.ttf
          weight: 600
        - asset: assets\fonts\Nunito\static\Nunito-Bold.ttf
          weight: 700
        - asset: assets\fonts\Nunito\static\Nunito-BoldItalic.ttf
          weight: 700
        - asset: assets\fonts\Nunito\static\Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\Nunito\static\Nunito-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/Nunito/static/Nunito-Black.ttf
          weight: 900
        - asset: assets\fonts\Nunito\static\Nunito-BlackItalic.ttf
          weight: 900
